MySQL input files:  Execute one statement at a time
When importing an SQL file with multiple statements (e.g. a DB schema
file), the driver is no longer able to fetch the result of each
statement after running it, leading to errors such as:

  File "/usr/local/lib/python3.6/site-packages/
    mysqlclient-1.3.14-py3.6-linux-x86_64.egg/MySQLdb/connections.py",
	line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.ProgrammingError:
    (2014, "Commands out of sync; you can't run this command now")
ERROR: Error closing cursor

Fixes #37, #38