database migrate: Print the tables which fail to migrate
Rather than calling the "DB migrate" SQL routine and having no idea
which table failed to migrate, if any:

sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError)
(1136, "Column count doesn't match value count at row 1")
[SQL: CALL opensips.OSIPS_DB_MIGRATE_2_4_TO_3_0('opensips',
    'opensips_copied')]

... we now call the "table migrate" routine for each table, so we give
better feedback on migration failures:

sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError)
(1136, "Column count doesn't match value count at row 1")
[SQL: CALL opensips.OSIPS_TB_COPY_2_4_TO_3_0('opensips',
    'opensips_copied', 'subscriber')]

    ^ in my case, my old 'subscriber' table had some extra columns