Improve compatibility with Python3.4
Force a pre-1.4.0 release of "mysqlclient", so we stay as compatible
with Python3.4 (default install on Debian 8) as possible.  With a
1.4.0+ mysqlclient package, Python3.4 systems would run into this:

File "/usr/local/lib/python3.4/dist-packages/mysqlclient-1.4.2.post1-
py3.4-linux-x86_64.egg/MySQLdb/cursors.py", line 203, in execute
    raise ProgrammingError(str(m))
sqlalchemy.exc.ProgrammingError: (MySQLdb._exceptions.ProgrammingError)
    unsupported operand type(s) for %: 'bytes' and 'tuple'

Thanks to @tangshiixang for helping troubleshoot this issue!
Related to #13