database migrate: Simplify stored procedure removal
There is no reason to query mysql.proc, especially since it does not
exist in MySQL 8.0:

INFO: Migrating all matching OpenSIPS tables...
ERROR: cannot execute query: SELECT count(*) FROM mysql.proc WHERE db
= 'opensips_3_0' AND name = 'OSIPS_DB_MIGRATE_3_0_TO_3_1'
ERROR: (_mysql_exceptions.ProgrammingError) (1146, "Table 'mysql.proc'
doesn't exist")
[SQL: SELECT count(*) FROM mysql.proc WHERE db = 'opensips_3_0'
AND name = 'OSIPS_DB_MIGRATE_3_0_TO_3_1']
(Background on this error at: http://sqlalche.me/e/f405)